management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  error:
    include-binding-errors: always
    include-message: always


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test2?createDatabaseIfNotExist=true
    username: root
    password: ''
    drver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update



